# Generated by Django 5.1.4 on 2026-07-09 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(help_text='What the buyer said they need.')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], default='whatsapp', max_length=20)),
                ('source', models.CharField(choices=[('contact_form', 'Contact form'), ('offer_page', 'Offer page'), ('package_page', 'Package page'), ('other', 'Other')], default='contact_form', max_length=20)),
                ('offer_slug', models.CharField(blank=True, max_length=100)),
                ('tier', models.CharField(blank=True, max_length=100)),
                ('page_url', models.URLField(blank=True, max_length=500)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal sent'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Salesperson responsible for this lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='leads_lead_status_7559b2_idx')],
            },
        ),
    ]
