# Generated by Django 5.1.4 on 2026-07-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='lead',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated deal value in USD.', max_digits=12),
        ),
    ]
