# Generated by Django 5.1.4 on 2026-07-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_lost_reason_lead_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('created', 'Created'), ('note', 'Note'), ('call', 'Call logged'), ('email', 'Email logged'), ('meeting', 'Meeting logged'), ('whatsapp', 'WhatsApp logged'), ('status_change', 'Status change'), ('assignment', 'Assignment'), ('edited', 'Edited')], default='note', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('contact_form', 'Contact form'), ('offer_page', 'Offer page'), ('package_page', 'Package page'), ('manual', 'Added by staff'), ('referral', 'Referral'), ('phone', 'Phone call'), ('walk_in', 'Walk-in'), ('other', 'Other')], default='contact_form', max_length=20),
        ),
    ]
